// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"user/ent/predicate"
	"user/ent/useropinfo"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserOpInfoDelete is the builder for deleting a UserOpInfo entity.
type UserOpInfoDelete struct {
	config
	hooks    []Hook
	mutation *UserOpInfoMutation
}

// Where adds a new predicate to the UserOpInfoDelete builder.
func (uoid *UserOpInfoDelete) Where(ps ...predicate.UserOpInfo) *UserOpInfoDelete {
	uoid.mutation.predicates = append(uoid.mutation.predicates, ps...)
	return uoid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uoid *UserOpInfoDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uoid.hooks) == 0 {
		affected, err = uoid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserOpInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uoid.mutation = mutation
			affected, err = uoid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uoid.hooks) - 1; i >= 0; i-- {
			mut = uoid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uoid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoid *UserOpInfoDelete) ExecX(ctx context.Context) int {
	n, err := uoid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uoid *UserOpInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: useropinfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useropinfo.FieldID,
			},
		},
	}
	if ps := uoid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, uoid.driver, _spec)
}

// UserOpInfoDeleteOne is the builder for deleting a single UserOpInfo entity.
type UserOpInfoDeleteOne struct {
	uoid *UserOpInfoDelete
}

// Exec executes the deletion query.
func (uoido *UserOpInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := uoido.uoid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useropinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uoido *UserOpInfoDeleteOne) ExecX(ctx context.Context) {
	uoido.uoid.ExecX(ctx)
}
