// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"user/ent/predicate"
	"user/ent/useroainfo"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserOaInfoQuery is the builder for querying UserOaInfo entities.
type UserOaInfoQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserOaInfo
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserOaInfoQuery builder.
func (uoiq *UserOaInfoQuery) Where(ps ...predicate.UserOaInfo) *UserOaInfoQuery {
	uoiq.predicates = append(uoiq.predicates, ps...)
	return uoiq
}

// Limit adds a limit step to the query.
func (uoiq *UserOaInfoQuery) Limit(limit int) *UserOaInfoQuery {
	uoiq.limit = &limit
	return uoiq
}

// Offset adds an offset step to the query.
func (uoiq *UserOaInfoQuery) Offset(offset int) *UserOaInfoQuery {
	uoiq.offset = &offset
	return uoiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uoiq *UserOaInfoQuery) Unique(unique bool) *UserOaInfoQuery {
	uoiq.unique = &unique
	return uoiq
}

// Order adds an order step to the query.
func (uoiq *UserOaInfoQuery) Order(o ...OrderFunc) *UserOaInfoQuery {
	uoiq.order = append(uoiq.order, o...)
	return uoiq
}

// First returns the first UserOaInfo entity from the query.
// Returns a *NotFoundError when no UserOaInfo was found.
func (uoiq *UserOaInfoQuery) First(ctx context.Context) (*UserOaInfo, error) {
	nodes, err := uoiq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{useroainfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uoiq *UserOaInfoQuery) FirstX(ctx context.Context) *UserOaInfo {
	node, err := uoiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserOaInfo ID from the query.
// Returns a *NotFoundError when no UserOaInfo ID was found.
func (uoiq *UserOaInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uoiq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{useroainfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uoiq *UserOaInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := uoiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserOaInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UserOaInfo entity is not found.
// Returns a *NotFoundError when no UserOaInfo entities are found.
func (uoiq *UserOaInfoQuery) Only(ctx context.Context) (*UserOaInfo, error) {
	nodes, err := uoiq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{useroainfo.Label}
	default:
		return nil, &NotSingularError{useroainfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uoiq *UserOaInfoQuery) OnlyX(ctx context.Context) *UserOaInfo {
	node, err := uoiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserOaInfo ID in the query.
// Returns a *NotSingularError when exactly one UserOaInfo ID is not found.
// Returns a *NotFoundError when no entities are found.
func (uoiq *UserOaInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uoiq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{useroainfo.Label}
	default:
		err = &NotSingularError{useroainfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uoiq *UserOaInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := uoiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserOaInfos.
func (uoiq *UserOaInfoQuery) All(ctx context.Context) ([]*UserOaInfo, error) {
	if err := uoiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uoiq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uoiq *UserOaInfoQuery) AllX(ctx context.Context) []*UserOaInfo {
	nodes, err := uoiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserOaInfo IDs.
func (uoiq *UserOaInfoQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := uoiq.Select(useroainfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uoiq *UserOaInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := uoiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uoiq *UserOaInfoQuery) Count(ctx context.Context) (int, error) {
	if err := uoiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uoiq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uoiq *UserOaInfoQuery) CountX(ctx context.Context) int {
	count, err := uoiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uoiq *UserOaInfoQuery) Exist(ctx context.Context) (bool, error) {
	if err := uoiq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uoiq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uoiq *UserOaInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := uoiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserOaInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uoiq *UserOaInfoQuery) Clone() *UserOaInfoQuery {
	if uoiq == nil {
		return nil
	}
	return &UserOaInfoQuery{
		config:     uoiq.config,
		limit:      uoiq.limit,
		offset:     uoiq.offset,
		order:      append([]OrderFunc{}, uoiq.order...),
		predicates: append([]predicate.UserOaInfo{}, uoiq.predicates...),
		// clone intermediate query.
		sql:  uoiq.sql.Clone(),
		path: uoiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Email string `json:"email,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserOaInfo.Query().
//		GroupBy(useroainfo.FieldEmail).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uoiq *UserOaInfoQuery) GroupBy(field string, fields ...string) *UserOaInfoGroupBy {
	group := &UserOaInfoGroupBy{config: uoiq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uoiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uoiq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Email string `json:"email,omitempty"`
//	}
//
//	client.UserOaInfo.Query().
//		Select(useroainfo.FieldEmail).
//		Scan(ctx, &v)
//
func (uoiq *UserOaInfoQuery) Select(field string, fields ...string) *UserOaInfoSelect {
	uoiq.fields = append([]string{field}, fields...)
	return &UserOaInfoSelect{UserOaInfoQuery: uoiq}
}

func (uoiq *UserOaInfoQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uoiq.fields {
		if !useroainfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uoiq.path != nil {
		prev, err := uoiq.path(ctx)
		if err != nil {
			return err
		}
		uoiq.sql = prev
	}
	return nil
}

func (uoiq *UserOaInfoQuery) sqlAll(ctx context.Context) ([]*UserOaInfo, error) {
	var (
		nodes   = []*UserOaInfo{}
		withFKs = uoiq.withFKs
		_spec   = uoiq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, useroainfo.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserOaInfo{config: uoiq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, uoiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uoiq *UserOaInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uoiq.querySpec()
	return sqlgraph.CountNodes(ctx, uoiq.driver, _spec)
}

func (uoiq *UserOaInfoQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uoiq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (uoiq *UserOaInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   useroainfo.Table,
			Columns: useroainfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useroainfo.FieldID,
			},
		},
		From:   uoiq.sql,
		Unique: true,
	}
	if unique := uoiq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uoiq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useroainfo.FieldID)
		for i := range fields {
			if fields[i] != useroainfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uoiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uoiq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uoiq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uoiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uoiq *UserOaInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uoiq.driver.Dialect())
	t1 := builder.Table(useroainfo.Table)
	selector := builder.Select(t1.Columns(useroainfo.Columns...)...).From(t1)
	if uoiq.sql != nil {
		selector = uoiq.sql
		selector.Select(selector.Columns(useroainfo.Columns...)...)
	}
	for _, p := range uoiq.predicates {
		p(selector)
	}
	for _, p := range uoiq.order {
		p(selector)
	}
	if offset := uoiq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uoiq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserOaInfoGroupBy is the group-by builder for UserOaInfo entities.
type UserOaInfoGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uoigb *UserOaInfoGroupBy) Aggregate(fns ...AggregateFunc) *UserOaInfoGroupBy {
	uoigb.fns = append(uoigb.fns, fns...)
	return uoigb
}

// Scan applies the group-by query and scans the result into the given value.
func (uoigb *UserOaInfoGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uoigb.path(ctx)
	if err != nil {
		return err
	}
	uoigb.sql = query
	return uoigb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uoigb *UserOaInfoGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := uoigb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (uoigb *UserOaInfoGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(uoigb.fields) > 1 {
		return nil, errors.New("ent: UserOaInfoGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := uoigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uoigb *UserOaInfoGroupBy) StringsX(ctx context.Context) []string {
	v, err := uoigb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uoigb *UserOaInfoGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uoigb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroainfo.Label}
	default:
		err = fmt.Errorf("ent: UserOaInfoGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uoigb *UserOaInfoGroupBy) StringX(ctx context.Context) string {
	v, err := uoigb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (uoigb *UserOaInfoGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(uoigb.fields) > 1 {
		return nil, errors.New("ent: UserOaInfoGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := uoigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uoigb *UserOaInfoGroupBy) IntsX(ctx context.Context) []int {
	v, err := uoigb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uoigb *UserOaInfoGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uoigb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroainfo.Label}
	default:
		err = fmt.Errorf("ent: UserOaInfoGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uoigb *UserOaInfoGroupBy) IntX(ctx context.Context) int {
	v, err := uoigb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (uoigb *UserOaInfoGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(uoigb.fields) > 1 {
		return nil, errors.New("ent: UserOaInfoGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := uoigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uoigb *UserOaInfoGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := uoigb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uoigb *UserOaInfoGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uoigb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroainfo.Label}
	default:
		err = fmt.Errorf("ent: UserOaInfoGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uoigb *UserOaInfoGroupBy) Float64X(ctx context.Context) float64 {
	v, err := uoigb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (uoigb *UserOaInfoGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(uoigb.fields) > 1 {
		return nil, errors.New("ent: UserOaInfoGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := uoigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uoigb *UserOaInfoGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := uoigb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uoigb *UserOaInfoGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uoigb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroainfo.Label}
	default:
		err = fmt.Errorf("ent: UserOaInfoGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uoigb *UserOaInfoGroupBy) BoolX(ctx context.Context) bool {
	v, err := uoigb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uoigb *UserOaInfoGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range uoigb.fields {
		if !useroainfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uoigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uoigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uoigb *UserOaInfoGroupBy) sqlQuery() *sql.Selector {
	selector := uoigb.sql
	columns := make([]string, 0, len(uoigb.fields)+len(uoigb.fns))
	columns = append(columns, uoigb.fields...)
	for _, fn := range uoigb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(uoigb.fields...)
}

// UserOaInfoSelect is the builder for selecting fields of UserOaInfo entities.
type UserOaInfoSelect struct {
	*UserOaInfoQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uois *UserOaInfoSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uois.prepareQuery(ctx); err != nil {
		return err
	}
	uois.sql = uois.UserOaInfoQuery.sqlQuery(ctx)
	return uois.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uois *UserOaInfoSelect) ScanX(ctx context.Context, v interface{}) {
	if err := uois.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (uois *UserOaInfoSelect) Strings(ctx context.Context) ([]string, error) {
	if len(uois.fields) > 1 {
		return nil, errors.New("ent: UserOaInfoSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := uois.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uois *UserOaInfoSelect) StringsX(ctx context.Context) []string {
	v, err := uois.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (uois *UserOaInfoSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uois.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroainfo.Label}
	default:
		err = fmt.Errorf("ent: UserOaInfoSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uois *UserOaInfoSelect) StringX(ctx context.Context) string {
	v, err := uois.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (uois *UserOaInfoSelect) Ints(ctx context.Context) ([]int, error) {
	if len(uois.fields) > 1 {
		return nil, errors.New("ent: UserOaInfoSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := uois.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uois *UserOaInfoSelect) IntsX(ctx context.Context) []int {
	v, err := uois.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (uois *UserOaInfoSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uois.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroainfo.Label}
	default:
		err = fmt.Errorf("ent: UserOaInfoSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uois *UserOaInfoSelect) IntX(ctx context.Context) int {
	v, err := uois.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (uois *UserOaInfoSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(uois.fields) > 1 {
		return nil, errors.New("ent: UserOaInfoSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := uois.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uois *UserOaInfoSelect) Float64sX(ctx context.Context) []float64 {
	v, err := uois.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (uois *UserOaInfoSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uois.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroainfo.Label}
	default:
		err = fmt.Errorf("ent: UserOaInfoSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uois *UserOaInfoSelect) Float64X(ctx context.Context) float64 {
	v, err := uois.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (uois *UserOaInfoSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(uois.fields) > 1 {
		return nil, errors.New("ent: UserOaInfoSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := uois.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uois *UserOaInfoSelect) BoolsX(ctx context.Context) []bool {
	v, err := uois.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (uois *UserOaInfoSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uois.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroainfo.Label}
	default:
		err = fmt.Errorf("ent: UserOaInfoSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uois *UserOaInfoSelect) BoolX(ctx context.Context) bool {
	v, err := uois.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uois *UserOaInfoSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uois.sqlQuery().Query()
	if err := uois.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uois *UserOaInfoSelect) sqlQuery() sql.Querier {
	selector := uois.sql
	selector.Select(selector.Columns(uois.fields...)...)
	return selector
}
