// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"user/ent/useropinfo"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserOpInfoCreate is the builder for creating a UserOpInfo entity.
type UserOpInfoCreate struct {
	config
	mutation *UserOpInfoMutation
	hooks    []Hook
}

// SetPhone sets the "phone" field.
func (uoic *UserOpInfoCreate) SetPhone(s string) *UserOpInfoCreate {
	uoic.mutation.SetPhone(s)
	return uoic
}

// Mutation returns the UserOpInfoMutation object of the builder.
func (uoic *UserOpInfoCreate) Mutation() *UserOpInfoMutation {
	return uoic.mutation
}

// Save creates the UserOpInfo in the database.
func (uoic *UserOpInfoCreate) Save(ctx context.Context) (*UserOpInfo, error) {
	var (
		err  error
		node *UserOpInfo
	)
	if len(uoic.hooks) == 0 {
		if err = uoic.check(); err != nil {
			return nil, err
		}
		node, err = uoic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserOpInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uoic.check(); err != nil {
				return nil, err
			}
			uoic.mutation = mutation
			node, err = uoic.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uoic.hooks) - 1; i >= 0; i-- {
			mut = uoic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uoic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uoic *UserOpInfoCreate) SaveX(ctx context.Context) *UserOpInfo {
	v, err := uoic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (uoic *UserOpInfoCreate) check() error {
	if _, ok := uoic.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New("ent: missing required field \"phone\"")}
	}
	return nil
}

func (uoic *UserOpInfoCreate) sqlSave(ctx context.Context) (*UserOpInfo, error) {
	_node, _spec := uoic.createSpec()
	if err := sqlgraph.CreateNode(ctx, uoic.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (uoic *UserOpInfoCreate) createSpec() (*UserOpInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &UserOpInfo{config: uoic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: useropinfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useropinfo.FieldID,
			},
		}
	)
	if value, ok := uoic.mutation.Phone(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: useropinfo.FieldPhone,
		})
		_node.Phone = value
	}
	return _node, _spec
}

// UserOpInfoCreateBulk is the builder for creating many UserOpInfo entities in bulk.
type UserOpInfoCreateBulk struct {
	config
	builders []*UserOpInfoCreate
}

// Save creates the UserOpInfo entities in the database.
func (uoicb *UserOpInfoCreateBulk) Save(ctx context.Context) ([]*UserOpInfo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(uoicb.builders))
	nodes := make([]*UserOpInfo, len(uoicb.builders))
	mutators := make([]Mutator, len(uoicb.builders))
	for i := range uoicb.builders {
		func(i int, root context.Context) {
			builder := uoicb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserOpInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uoicb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uoicb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uoicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uoicb *UserOpInfoCreateBulk) SaveX(ctx context.Context) []*UserOpInfo {
	v, err := uoicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
