// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"user/ent/predicate"
	"user/ent/userlog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserLogDelete is the builder for deleting a UserLog entity.
type UserLogDelete struct {
	config
	hooks    []Hook
	mutation *UserLogMutation
}

// Where adds a new predicate to the UserLogDelete builder.
func (uld *UserLogDelete) Where(ps ...predicate.UserLog) *UserLogDelete {
	uld.mutation.predicates = append(uld.mutation.predicates, ps...)
	return uld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uld *UserLogDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uld.hooks) == 0 {
		affected, err = uld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uld.mutation = mutation
			affected, err = uld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uld.hooks) - 1; i >= 0; i-- {
			mut = uld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (uld *UserLogDelete) ExecX(ctx context.Context) int {
	n, err := uld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uld *UserLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userlog.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userlog.FieldID,
			},
		},
	}
	if ps := uld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, uld.driver, _spec)
}

// UserLogDeleteOne is the builder for deleting a single UserLog entity.
type UserLogDeleteOne struct {
	uld *UserLogDelete
}

// Exec executes the deletion query.
func (uldo *UserLogDeleteOne) Exec(ctx context.Context) error {
	n, err := uldo.uld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uldo *UserLogDeleteOne) ExecX(ctx context.Context) {
	uldo.uld.ExecX(ctx)
}
