// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"user/ent/userlog"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserLogCreate is the builder for creating a UserLog entity.
type UserLogCreate struct {
	config
	mutation *UserLogMutation
	hooks    []Hook
}

// SetIP sets the "ip" field.
func (ulc *UserLogCreate) SetIP(s string) *UserLogCreate {
	ulc.mutation.SetIP(s)
	return ulc
}

// SetRemark sets the "remark" field.
func (ulc *UserLogCreate) SetRemark(s string) *UserLogCreate {
	ulc.mutation.SetRemark(s)
	return ulc
}

// SetCreateAt sets the "create_at" field.
func (ulc *UserLogCreate) SetCreateAt(t time.Time) *UserLogCreate {
	ulc.mutation.SetCreateAt(t)
	return ulc
}

// Mutation returns the UserLogMutation object of the builder.
func (ulc *UserLogCreate) Mutation() *UserLogMutation {
	return ulc.mutation
}

// Save creates the UserLog in the database.
func (ulc *UserLogCreate) Save(ctx context.Context) (*UserLog, error) {
	var (
		err  error
		node *UserLog
	)
	if len(ulc.hooks) == 0 {
		if err = ulc.check(); err != nil {
			return nil, err
		}
		node, err = ulc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ulc.check(); err != nil {
				return nil, err
			}
			ulc.mutation = mutation
			node, err = ulc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ulc.hooks) - 1; i >= 0; i-- {
			mut = ulc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ulc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ulc *UserLogCreate) SaveX(ctx context.Context) *UserLog {
	v, err := ulc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (ulc *UserLogCreate) check() error {
	if _, ok := ulc.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New("ent: missing required field \"ip\"")}
	}
	if _, ok := ulc.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New("ent: missing required field \"remark\"")}
	}
	if _, ok := ulc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New("ent: missing required field \"create_at\"")}
	}
	return nil
}

func (ulc *UserLogCreate) sqlSave(ctx context.Context) (*UserLog, error) {
	_node, _spec := ulc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ulc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ulc *UserLogCreate) createSpec() (*UserLog, *sqlgraph.CreateSpec) {
	var (
		_node = &UserLog{config: ulc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: userlog.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userlog.FieldID,
			},
		}
	)
	if value, ok := ulc.mutation.IP(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userlog.FieldIP,
		})
		_node.IP = value
	}
	if value, ok := ulc.mutation.Remark(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userlog.FieldRemark,
		})
		_node.Remark = value
	}
	if value, ok := ulc.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userlog.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	return _node, _spec
}

// UserLogCreateBulk is the builder for creating many UserLog entities in bulk.
type UserLogCreateBulk struct {
	config
	builders []*UserLogCreate
}

// Save creates the UserLog entities in the database.
func (ulcb *UserLogCreateBulk) Save(ctx context.Context) ([]*UserLog, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ulcb.builders))
	nodes := make([]*UserLog, len(ulcb.builders))
	mutators := make([]Mutator, len(ulcb.builders))
	for i := range ulcb.builders {
		func(i int, root context.Context) {
			builder := ulcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ulcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ulcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ulcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ulcb *UserLogCreateBulk) SaveX(ctx context.Context) []*UserLog {
	v, err := ulcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
