// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"user/ent/predicate"
	"user/ent/useroainfo"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserOaInfoUpdate is the builder for updating UserOaInfo entities.
type UserOaInfoUpdate struct {
	config
	hooks    []Hook
	mutation *UserOaInfoMutation
}

// Where adds a new predicate for the UserOaInfoUpdate builder.
func (uoiu *UserOaInfoUpdate) Where(ps ...predicate.UserOaInfo) *UserOaInfoUpdate {
	uoiu.mutation.predicates = append(uoiu.mutation.predicates, ps...)
	return uoiu
}

// SetEmail sets the "email" field.
func (uoiu *UserOaInfoUpdate) SetEmail(s string) *UserOaInfoUpdate {
	uoiu.mutation.SetEmail(s)
	return uoiu
}

// SetEmailPwd sets the "email_pwd" field.
func (uoiu *UserOaInfoUpdate) SetEmailPwd(s string) *UserOaInfoUpdate {
	uoiu.mutation.SetEmailPwd(s)
	return uoiu
}

// Mutation returns the UserOaInfoMutation object of the builder.
func (uoiu *UserOaInfoUpdate) Mutation() *UserOaInfoMutation {
	return uoiu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uoiu *UserOaInfoUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uoiu.hooks) == 0 {
		affected, err = uoiu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserOaInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uoiu.mutation = mutation
			affected, err = uoiu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uoiu.hooks) - 1; i >= 0; i-- {
			mut = uoiu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uoiu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uoiu *UserOaInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := uoiu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uoiu *UserOaInfoUpdate) Exec(ctx context.Context) error {
	_, err := uoiu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoiu *UserOaInfoUpdate) ExecX(ctx context.Context) {
	if err := uoiu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uoiu *UserOaInfoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   useroainfo.Table,
			Columns: useroainfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useroainfo.FieldID,
			},
		},
	}
	if ps := uoiu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uoiu.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: useroainfo.FieldEmail,
		})
	}
	if value, ok := uoiu.mutation.EmailPwd(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: useroainfo.FieldEmailPwd,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uoiu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useroainfo.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// UserOaInfoUpdateOne is the builder for updating a single UserOaInfo entity.
type UserOaInfoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserOaInfoMutation
}

// SetEmail sets the "email" field.
func (uoiuo *UserOaInfoUpdateOne) SetEmail(s string) *UserOaInfoUpdateOne {
	uoiuo.mutation.SetEmail(s)
	return uoiuo
}

// SetEmailPwd sets the "email_pwd" field.
func (uoiuo *UserOaInfoUpdateOne) SetEmailPwd(s string) *UserOaInfoUpdateOne {
	uoiuo.mutation.SetEmailPwd(s)
	return uoiuo
}

// Mutation returns the UserOaInfoMutation object of the builder.
func (uoiuo *UserOaInfoUpdateOne) Mutation() *UserOaInfoMutation {
	return uoiuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uoiuo *UserOaInfoUpdateOne) Select(field string, fields ...string) *UserOaInfoUpdateOne {
	uoiuo.fields = append([]string{field}, fields...)
	return uoiuo
}

// Save executes the query and returns the updated UserOaInfo entity.
func (uoiuo *UserOaInfoUpdateOne) Save(ctx context.Context) (*UserOaInfo, error) {
	var (
		err  error
		node *UserOaInfo
	)
	if len(uoiuo.hooks) == 0 {
		node, err = uoiuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserOaInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uoiuo.mutation = mutation
			node, err = uoiuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uoiuo.hooks) - 1; i >= 0; i-- {
			mut = uoiuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uoiuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uoiuo *UserOaInfoUpdateOne) SaveX(ctx context.Context) *UserOaInfo {
	node, err := uoiuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uoiuo *UserOaInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := uoiuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoiuo *UserOaInfoUpdateOne) ExecX(ctx context.Context) {
	if err := uoiuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uoiuo *UserOaInfoUpdateOne) sqlSave(ctx context.Context) (_node *UserOaInfo, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   useroainfo.Table,
			Columns: useroainfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useroainfo.FieldID,
			},
		},
	}
	id, ok := uoiuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing UserOaInfo.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := uoiuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useroainfo.FieldID)
		for _, f := range fields {
			if !useroainfo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useroainfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uoiuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uoiuo.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: useroainfo.FieldEmail,
		})
	}
	if value, ok := uoiuo.mutation.EmailPwd(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: useroainfo.FieldEmailPwd,
		})
	}
	_node = &UserOaInfo{config: uoiuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uoiuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useroainfo.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
