// Code generated by entc, DO NOT EDIT.

package userlog

const (
	// Label holds the string label denoting the userlog type in the database.
	Label = "user_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// Table holds the table name of the userlog in the database.
	Table = "user_logs"
)

// Columns holds all SQL columns for userlog fields.
var Columns = []string{
	FieldID,
	FieldIP,
	FieldRemark,
	FieldCreateAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "user_logs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_user_logs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
