// Code generated by entc, DO NOT EDIT.

package userrole

const (
	// Label holds the string label denoting the userrole type in the database.
	Label = "user_role"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserId holds the string denoting the userid field in the database.
	FieldUserId = "user_id"
	// FieldRoleId holds the string denoting the roleid field in the database.
	FieldRoleId = "role_id"
	// Table holds the table name of the userrole in the database.
	Table = "user_roles"
)

// Columns holds all SQL columns for userrole fields.
var Columns = []string{
	FieldID,
	FieldUserId,
	FieldRoleId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
