// Code generated by entc, DO NOT EDIT.

package useroainfo

const (
	// Label holds the string label denoting the useroainfo type in the database.
	Label = "user_oa_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldEmailPwd holds the string denoting the email_pwd field in the database.
	FieldEmailPwd = "email_pwd"
	// Table holds the table name of the useroainfo in the database.
	Table = "user_oa_infos"
)

// Columns holds all SQL columns for useroainfo fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldEmailPwd,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "user_oa_infos"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_user_oa_info",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
