// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"role/ent"
)

type PermissionInput struct {
	Name   string `json:"name"`
	Code   string `json:"code"`
	Remark string `json:"remark"`
}

type RoleDetail struct {
	Role        *ent.Role         `json:"role"`
	Permissions []*ent.Permission `json:"permissions"`
}

type RoleInput struct {
	Name   string `json:"name"`
	Remark string `json:"remark"`
}

type RolePermissionInput struct {
	RoleID       int `json:"roleId"`
	PermissionID int `json:"permissionId"`
}

type User struct {
	ID    int           `json:"id"`
	Roles []*RoleDetail `json:"roles"`
}

func (User) IsEntity() {}

type UserRoleDetail struct {
	ID    int           `json:"id"`
	User  *User         `json:"user"`
	Roles []*RoleDetail `json:"roles"`
}

type UserRoleInput struct {
	UserID int `json:"userId"`
	RoleID int `json:"roleId"`
}
