// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserLog is the predicate function for userlog builders.
type UserLog func(*sql.Selector)

// UserOaInfo is the predicate function for useroainfo builders.
type UserOaInfo func(*sql.Selector)

// UserOpInfo is the predicate function for useropinfo builders.
type UserOpInfo func(*sql.Selector)
