// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (pe *Permission) Role(ctx context.Context) ([]*Role, error) {
	result, err := pe.Edges.RoleOrErr()
	if IsNotLoaded(err) {
		result, err = pe.QueryRole().All(ctx)
	}
	return result, err
}

func (r *Role) Permissions(ctx context.Context) ([]*Permission, error) {
	result, err := r.Edges.PermissionsOrErr()
	if IsNotLoaded(err) {
		result, err = r.QueryPermissions().All(ctx)
	}
	return result, err
}
