// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type UserInput struct {
	Age      *int   `json:"age"`
	Name     string `json:"name"`
	Username string `json:"username"`
}
